### ISSUE TITLE
More clarification

### ISSUE THREAD

**Issue by bhantsi** [eHealthAfrica/GIS-Dev-Intern-Test#4]
Should I create new repo for each task?

**Comment by Timtech4u** [comment]
Hi @bhantsi  , you can clone the main repo and push to your own remote repo.
Checkout: https://help.github.com/articles/adding-a-remote

**Comment by Amoosimeon** [comment]
Creating a private repo requires credit card information and account upgrading, will the public repo do

**Comment by ahmedOpeyemi** [comment]
Hi @Amoosimeon, if you are unable to create a private repo on Github, you can use [bitbucket](http://bitbucket.org/).
