### ISSUE TITLE
Email given is not a Git User

### ISSUE THREAD

**Issue by SamAkinosun** [eHealthAfrica/GIS-Dev-Intern-Test#5]
The email: samuel.okoroafor@ehealthafrica.org provided for sharing read access is not a Git Hub user and hence can't add as a collaborator.
"samuel.okoroafor@ehealthafrica.org doesn’t have a GitHub account"

Kindly check that.

Regards

**Comment by abrahamy** [comment]
Try adding @s-chand as a contributor instead

**Comment by SamAkinosun** [comment]
Solution: Use BitBucket. BitBucket allows sharing of repository with non-users.

**Comment by SamAkinosun** [comment]
I've already sent it via Bitbucket.

Please confirm if you have received it sir.

**Comment by abrahamy** [comment]
That is not necessary. Please follow the instructions and add only the people mentioned in the instructions.
